[package]
name = "external_set"
version = "0.1.0"
authors = ["Kevin Mehall <km@kevinmehall.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kevinmehall/external_set"

[dependencies]

[lib]
name = "external_set"
path = "lib.rs"
